apiVersion: v1
kind: Service
metadata:
  name: netflix-clone-service
spec:
  type: NodePort
  selector:
    app: netflix-clone
  ports:
    - name: backend
      port: 5000
      targetPort: 5000
      nodePort: 30500
    - name: frontend
      port: 5173
      targetPort: 5173
      nodePort: 30517
