
apiVersion: v1
kind: Service
metadata:
  name: netflix-backend
  namespace: netflix
spec:
  type: ClusterIP
  selector:
    app: netflix-backend
  ports:
  - name: http
    port: 5000
    targetPort: 5000
