apiVersion: v1
kind: Service
metadata:
  name: netflix-frontend
  namespace: netflix
spec:
  selector:
    app: netflix-frontend
  ports:
  - name: http
    port: 80
    targetPort: 80
  type: ClusterIP
