
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: netflix-ingress
  namespace: netflix
  annotations:
    kubernetes.io/ingress.class: nginx
spec:
  rules:
  - host: netflix.local
    http:
      paths:
      - path: /
        pathType: Prefix
        backend:
          service:
            name: netflix-frontend
            port:
              number: 80
      - path: /api
        pathType: Prefix
        backend:
          service:
            name: netflix-backend
            port:
              number: 5000
