apiVersion: apps/v1
kind: Deployment
metadata:
  name: netflix-clone
spec:
  replicas: 2
  selector:
    matchLabels:
      app: netflix-clone
  template:
    metadata:
      labels:
        app: netflix-clone
    spec:
      containers:
        - name: netflix-clone
          image: netflixcloneimage-hva5gdh8hxf7dfh7.azurecr.io/netflix-clone:latest
          imagePullPolicy: Always
          ports:
            - containerPort: 5000
          envFrom:
           - secretRef:
               name: netflix-secret
